openapi: '3.0.0'
info:
  version: 1.0.0
  title: Test
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /testRuns:
    get:
      summary: List all test runs
      operationId: listTestRuns
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of test runs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRuns'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create test run
      operationId: createTestRun
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /testRuns/{testRunId}:
    get:
      summary: Get test run info
      operationId: showTestRunById
      parameters:
        - name: testRunId
          in: path
          required: true
          description: The id of the test run to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRuns'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /testers:
    get:
      summary: List all testers
      operationId: listTesters
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of testers
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Testers'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TestRun:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
    TestRuns:
      type: array
      items:
        $ref: '#/components/schemas/TestRun'
    Tester:
      required:
        - id
        - username
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        rating:
          type: integer
          format: int32
    Testers:
      type: array
      items:
        $ref: '#/components/schemas/Tester'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string